server:
  port: 8082

spring:
  application:
    name: video-chat-backend-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: video-chat-recommendation
          uri: http://localhost:8086/
          predicates:
            - Path=/api/v1/chat/join-chat, /api/v1/chat/end-chat, /api/v1/chat/terminate
            - Method=POST
            - Header=Authorization, Bearer (.*)
          filters:
            - JwtOnRequestTokenFilter
        - id: video-chat-user
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/security/login, /api/v1/security/register, /api/v1/security/update-token,
            - Method=POST
        - id: video-chat-user-with-jwt
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/talk, /api/v1/user
            - Method=GET, POST, PUT
            - Header=Authorization, Bearer (.*)
          filters:
            - JwtOnRequestTokenFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

token-secret-key: ${TOKEN_SECRET_KEY}